# Generated by Django 5.0.3 on 2024-03-25 16:36

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aricles",
            name="body",
            field=ckeditor.fields.RichTextField(),
        ),
    ]
