# Generated by Django 5.0.3 on 2024-04-03 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0003_comment"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="aricles",
            options={"ordering": ["-date"]},
        ),
        migrations.AlterModelOptions(
            name="comment",
            options={"ordering": ["-id"]},
        ),
        migrations.AddField(
            model_name="aricles",
            name="categories",
            field=models.ManyToManyField(
                related_name="articles", to="articles.category"
            ),
        ),
    ]
